grails-app/controllers/com/scand/edu/AuthenticationController.groovy
package com.scand.edu

import grails.plugin.springsecurity.SpringSecurityService
import grails.plugin.springsecurity.annotation.Secured

@Secured(['permitAll'])
class AuthenticationController {

    UserService userService
    SpringSecurityService springSecurityService

    def index() {
        render view: 'loginForm'
    }

    def login() {
        redirect(controller: "Pig", action: "index")
    }

    def logout() {

    }

    def showRegisterForm() {
        render view: 'registrationForm'
    }

    def singUp(User user, String passwordRepeat) {
        if (user.password && user.password != passwordRepeat) {
            user.errors.rejectValue(
                    'password',
                    'user.password.doesnotmatch')
        }
        if (user.password == passwordRepeat) {
            userService.create(user)
        }
        if (user && !user.hasErrors()) {
            springSecurityService.reauthenticate user.username
            redirect(controller: "Pig", action: "index")
        } else {
            render(view: 'registrationForm', model: [user: user])
        }

    }
}

grails-app/views/authentication/login.gsp
<%--
  Created by IntelliJ IDEA.
  User: podberezkaya
  Date: 12/27/2018
  Time: 4:31 PM
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
	<title></title>
</head>

<body>
<div class="container vlogo">
	<g:form method="post">
		<input name="offset" type="hidden" value="${offset}"/>
		<div class="form-group ">
			<label for="authorName"><g:message code="feedback.message.authorName.label"/></label>
		<div class="errorMessage">
			<g:textField name="authorName" class="form-control"/>
			<g:renderErrors bean="${feedback}" as="list" field="authorName" style="color: red"/>
		</div>
		<div class="form-group ">
			<label for="message"><g:message code="feedback.message.message.label"/></label>
			<div class="errorMessage">
				<g:textArea name="message" class="form-control"/>
				<g:renderErrors bean="${feedback}" as="list" field="message"/>
			</div>
		</div>
		<g:actionSubmit action="addFeedback" value="add a feedback"/>
	</g:form>
</div>
</body>
</html>

grails-app/views/authentication/loginForm.gsp
<%--
  Created by IntelliJ IDEA.
  User: podberezkaya
  Date: 12/30/2018
  Time: 10:12 AM
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
	<head>
		<meta name="layout" content="public"/>
		<title>Login form</title>
	</head>
	<body>
		<div class="container vlogo" style="width: 30em">
			<form action="/Pigadise/j_spring_security_check" method="POST" id="loginForm" class="cssform" autocomplete="off">
				<p>
					<label for="username"><g:message code="login.form.userName"/></label>
					<input type="text" class="form-control" name="j_username" id="username">
				</p>

				<p>
					<label for="password"><g:message code="login.form.password"/></label>
					<input type="password" class="form-control" name="j_password" id="password">
				</p>

				<p id="remember_me_holder">
					<input type="checkbox" class="chk" name="_spring_security_remember_me" id="remember_me">
					<label for="remember_me"><g:message code="login.form.remember"/></label>
				</p>

				<p>
					<input type="submit" id="submit" value="Login" class="button btn-info  btn-lg" style="width: 100%">
				</p>
			</form>
		</div>
	</body>
</html>

grails-app/views/authentication/registrationForm.gsp
<%--
  Created by IntelliJ IDEA.
  User: podberezkaya
  Date: 12/30/2018
  Time: 11:00 AM
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
	<title>Registration</title>
	<meta name="layout" content="public"/>
</head>

<body>
<div class="container vlogo" style="width: 30em">
	<g:form controller="authentication" method="post">
		<input name="offset" type="hidden" value="${offset}"/>
		<div class="form-group ">
			<label for="firstName"><g:message code="registration.form.firstName"/></label>
		<div class="errorMessage">
			<g:textField name="firstName" class="form-control"/>
			<g:renderErrors bean="${user}" as="list" field="firstName" style="color: red"/>
		</div>
		<div class="form-group ">
			<label for="lastName"><g:message code="registration.form.lastName"/></label>
			<div class="errorMessage">
				<g:textField name="lastName" class="form-control"/>
				<g:renderErrors bean="${user}" as="list" field="lastName"/>
			</div>
		</div>
		<div class="form-group ">
			<label for="username"><g:message code="registration.form.userName"/></label>
			<div class="errorMessage">
				<g:textField name="username" class="form-control"/>
				<g:renderErrors bean="${user}" as="list" field="username"/>
			</div>
		</div>
		<div class="form-group ">
			<label for="email"><g:message code="registration.form.email"/></label>
			<div class="errorMessage">
				<g:textField name="email" class="form-control"/>
				<g:renderErrors bean="${user}" as="list" field="email"/>
			</div>
		</div>
		<div class="form-group ">
			<label for="password"><g:message code="registration.form.password"/></label>
			<div class="errorMessage">
				<g:passwordField  name="password" class="form-control"/>
				<g:renderErrors bean="${user}" as="list" field="password"/>
			</div>
		</div>
		<div class="form-group ">
			<label for="password"><g:message code="registration.form.repeatPassword"/></label>
			<div class="errorMessage">
				<g:passwordField  name="passwordRepeat" class="form-control"/>
				<g:renderErrors bean="${user}" as="list" field="password"/>
			</div>
		</div>
		<g:actionSubmit action="singUp" value="Sign up"  class="button btn-info  btn-lg" style="width: 100%"/>
	</g:form>
</div>
</div>
</body>

</html>